version: '3.1'
services:
    php:
        restart: always
        ports:
            - 8100:80
        build:
            context: ./
            dockerfile: .docker/web.docker
        environment:
            VIRTUAL_HOST: admin.local
        volumes:
            - .:/srv/app
        networks:
            - default
            - nginx-proxy
networks:
    default:
    nginx-proxy:
        name: nginx-proxy
